repos:
- repo: https://github.com/PyCQA/pylint
  rev: pylint-2.7.2
  hooks:
  - id: pylint
    exclude: ^server/
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4  # Use the sha / tag you want to point at
  hooks:
  - id: autopep8
    exclude: ^server/